services:
  app1:
    build: 
      context: ./app
      dockerfile: Dockerfile
    networks:
      - app_network
    volumes:
      - app_data:/app/data
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  app2:
    build: 
      context: ./app
      dockerfile: Dockerfile
    networks:
      - app_network
    volumes:
      - app_data:/app/data
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  app3:
    build: 
      context: ./app
      dockerfile: Dockerfile
    networks:
      - app_network
    volumes:
      - app_data:/app/data
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - app_network
    depends_on:
      - app1
      - app2
      - app3

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    networks:
      - app_network

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - app_network
    depends_on:
      - prometheus

networks:
  app_network:
    driver: bridge

volumes:
  app_data:
  prometheus_data:
  grafana_data: 